### ISSUE TITLE
Random shutdowns of the 482 integration

### ISSUE THREAD

**Issue by rjmcdougall** [WillCodeForCats/tekmar-482#23]
Before reporting a bug, make sure you are running the latest version of `tekmar-482` integration and the `tekmar-packetserv` add-on.

**Describe the bug**
Every 3-4 hours or so the integration shuts down with an uncaught exception during packet processing at line 306. It appears that it's possibly a data serialization/sync issue -- the serviceID is a very large number and out of bounds.

**Expected behavior**
Ideally no crashes and no corrupted packets, but perhaps we want to test & capture exceptions during early processing of new packets received?

**Screenshots**
If applicable, add screenshots of the problem and/or configuration.

**Logs**
Copy any log messages/errors from Home Assistant from `custom_components.tekmar_482`

**Home Assistant (please complete the following information):**
Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Additional context**

**Comment by WillCodeForCats** [comment]
What's the full exception error from the HA logs?

**Comment by rjmcdougall** [comment]
Looks like the log was overwritten. Waiting for it to happen again and I'll cut and paste!

**Comment by rjmcdougall** [comment]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tekmar_482/hub.py:308
Integration: Tekmar Gateway 482 (documentation, issues)
First occurred: 3:40:21 PM (1 occurrences)
Last logged: 3:40:21 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tekmar_482/hub.py", line 308, in run
    tha_method = name_from_methodID[p.header["methodID"]]
KeyError: 22273

**Comment by WillCodeForCats** [comment]
Will be fixed in PR #24
