### ISSUE TITLE
Feature request: Support for Floor temperature setpoint and current temp in devices which support it

### ISSUE THREAD

**Issue by rjmcdougall** [WillCodeForCats/tekmar-482#27]
**Describe the bug**
Feature request: Support for 

**Expected behavior**
Most devices support the option for a floor temp sensor, and also export an additional setpoint for the floor minimum. It would be great to expose those to HA.

My current thermostat devices are 553 (3), 557 (4), 529 (3) and 161 (2).

The primary use case I have is for the 5xx thermostats as a floor min in conjunction with the room temp setpoints.

**Comment by rjmcdougall** [comment]
It appears there is support for the floor temperature sensors. I notice in my config it is only enabling for  the 161 thermostats. It may be a race condition -- IIRC the 5xx thermostats don't initially report floor temp attributes, but do so later as an update to attributes?

**Comment by WillCodeForCats** [comment]
The 161 is weird and it doesn't always report properly until you send it a setpoint group enable/disable command.

**Comment by WillCodeForCats** [comment]
Current Floor Temperature is a sensor, but it only works on protocol v3 gateways.

**Comment by WillCodeForCats** [comment]
If a device's attributes change after startup, you will get an error message in logs that says "Device attributes for X changed". But they shouldn't change unless you are changing stuff in the setup menu on the tstat itself after startup.

Floor temp sensor for the setpoint units (161, 162) was missing a check for protocol v3 which causes it to always be added even if not supported.

What version is your gateway? This will be on the device page:

<img width="336" alt="Screen Shot 2022-12-12 at 11 36 34 AM" src="https://user-images.githubusercontent.com/48533968/207137902-9eca17b4-e760-48f6-9a9a-28d5990c00b9.png">

**Comment by rjmcdougall** [comment]
Seems like the same gateway version.

[image: Screen Shot 2022-12-12 at 4.34.11 PM.png]

**Comment by rjmcdougall** [comment]
[image: Screen Shot 2022-12-12 at 4.34.53 PM.png]

**Comment by WillCodeForCats** [comment]
I will change the sensor so that it's always available but disabled by default, so it can be enabled in HA if desired. If it doesn't have any data from the gateway it'll be in state unavailable.

**Comment by WillCodeForCats** [comment]
Does the change in Release v0.9.7 do what you need it to do?

**Comment by rjmcdougall** [comment]
Hi and thanks for the help! It did crash again last night - I am about to
extract the logs.

**Comment by WillCodeForCats** [comment]
Closing due to age.
