### ISSUE TITLE
Integration stuck on initializing

### ISSUE THREAD

**Issue by safadig** [WillCodeForCats/tekmar-482#45]
Tried changing port to 7001 on packet server and integration. Using prolific chip usb to rs232 to connect. Any idea what else may be causing the error (tried usual shutdown etc..)

**Comment by WillCodeForCats** [comment]
Most likely means there is no serial communication with the Gateway 482.

**Comment by safadig** [comment]
> Most likely means there is no serial communication with the Gateway 482.

It was. Now good. Thanks
