### ISSUE TITLE
snowmelt 680 not supported

### ISSUE THREAD

**Issue by jonoberheide** [WillCodeForCats/tekmar-482#64]
Hi! I have a Tekmar 680 snowmelt device that is not listed in the documentation as a supported device. Any chance this could be added? Happy to help develop/test in any way.

https://www.watts.com/products/hvac-hot-water-solutions/controls/snow-melting-controls/680/680

**Comment by WillCodeForCats** [comment]
I don't have a 680 (I have a 654 for testing) but looking at the docs for the the 680 I don't see a tN4 bus terminal in the wiring diagram, so it wouldn't be compatible with this integration without a tekmarnet bus connection.

But it does have modbus support so you should be able to use the core modbus integration with the 680.

Modbus registers: https://www.watts.com/dfsmedia/0533dbba17714b1ab581ab07a4cbb521/81848-source/680-b-03
Core modbus: https://www.home-assistant.io/integrations/modbus/

**Comment by jonoberheide** [comment]
Oh interesting. Thanks for the info!
